# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = "$all$username$hostname$character"

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[username]
format = "[$user]($bold blue)"
show_always = true

[hostname]
format = "[@$ssh_symbol$hostname]($bold blue) "
ssh_only = false
